spring.application.name=patient-note
#spring.config.import=optional:configserver:http://localhost:9101
spring.config.import=optional:configserver:http://config-server:9101
spring.mongodb.uri=mongodb://medilabo:medilabo@mongodb:27017/patient_note_db?authSource=admin
