server.port=9003
eureka.client.serviceUrl.defaultZone=http://localhost:9002/eureka/
management.endpoints.web.exposure.include=*

spring.cloud.gateway.server.webmvc.routes[0].id=patients-list
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://patient
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/patients

spring.cloud.gateway.server.webmvc.routes[1].id=patients-detail
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://patient
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/patient/**

spring.cloud.gateway.server.webmvc.routes[2].id=notes
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://patient-note
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/note/**


spring.cloud.gateway.server.webmvc.routes[3].id=rapport-patient-detail
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://patient
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/rapport/patient/**

spring.cloud.gateway.server.webmvc.routes[4].id=rapport
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://patient-rapport
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/rapport/**

spring.cloud.gateway.server.webmvc.routes[5].id=ui
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/patients,/patient/**,/add/**,/update/**,/css/**

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG