server.port=9003
eureka.client.serviceUrl.defaultZone=http://localhost:9002/eureka/
management.endpoints.web.exposure.include=*


spring.cloud.gateway.server.webmvc.routes[0].id=patients
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://patient
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.server.webmvc.routes[1].id=patient
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://patient
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/patient/**

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG