server.port=9004
eureka.client.serviceUrl.defaultZone=http://eureka:9002/eureka/
spring.data.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin

