server.port=9004
#eureka.client.serviceUrl.defaultZone=http://localhost:9002/eureka/
eureka.client.serviceUrl.defaultZone=http://eureka:9002/eureka/

spring.mongodb.uri=mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.rap0fmc.mongodb.net/medilabo
